"""
Auto-generated Python reference model for: ian.challenge_bond
IR hash: sha256:c9cbe592f2e9036cc081f5742cda2ebee471d9a8d849ebd217d084e559c97c00

Generated by ESSO (Evolutionary Spec Search Optimizer)

This file is standalone and has no ESSO dependencies.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Literal, Mapping


# Domain enums
STATUS_SYMBOLS = ('ACTIVE', 'LOCKED', 'SLASHED', 'WITHDRAWN')


@dataclass(frozen=True)
class State:
    """Model state."""
    amount: int
    min_challenge_bond: int
    status: str


@dataclass(frozen=True)
class Command:
    """Command to execute."""
    tag: Literal('lock_for_challenge', 'resolve_invalid', 'resolve_valid', 'withdraw_active', 'withdraw_remainder')
    args: Mapping[str, Any]


@dataclass(frozen=True)
class StepResult:
    """Result of a step execution."""
    ok: bool
    state: State | None = None
    effects: Mapping[str, Any] | None = None
    error: str | None = None


def init_state() -> State:
    """Return the initial state."""
    return State(
        amount=0,
        min_challenge_bond=0,
        status='ACTIVE',
    )


def check_invariants(s: State) -> tuple[bool, str | None]:
    """Check all invariants. Returns (ok, first_failed_id)."""
    if not (isinstance(s.amount, int) and not isinstance(s.amount, bool) and 0 <= s.amount <= 1000000):
        return False, 'domain_amount'
    if not (isinstance(s.min_challenge_bond, int) and not isinstance(s.min_challenge_bond, bool) and 0 <= s.min_challenge_bond <= 100000):
        return False, 'domain_min_challenge_bond'
    if not (s.status in ('ACTIVE', 'LOCKED', 'SLASHED', 'WITHDRAWN')):
        return False, 'domain_status'
    if not ((('LOCKED' != s.status) or (s.amount >= s.min_challenge_bond))):
        return False, 'locked_implies_sufficient'
    if not ((s.amount >= 0)):
        return False, 'valid_amount'
    if not ((('WITHDRAWN' != s.status) or (0 == s.amount))):
        return False, 'withdrawn_is_empty'
    return True, None


def step(s: State, cmd: Command) -> StepResult:
    """Execute a step. Returns StepResult."""
    # Check pre-state invariants
    ok, failed = check_invariants(s)
    if not ok:
        return StepResult(ok=False, error=f'pre-invariant violated: {failed}')

    if cmd.tag == 'lock_for_challenge':
        if not ((('LOCKED' != s.status) and ('SLASHED' != s.status) and ('WITHDRAWN' != s.status) and (s.amount >= s.min_challenge_bond))):
            return StepResult(ok=False, error='guard failed for lock_for_challenge')
        # Compute updates (simultaneous)
        new_state = State(
            amount=s.amount,
            min_challenge_bond=s.min_challenge_bond,
            status='LOCKED',
        )
        effects = {}
        ok, failed = check_invariants(new_state)
        if not ok:
            return StepResult(ok=False, error=f'post-invariant violated: {failed}')
        return StepResult(ok=True, state=new_state, effects=effects)
    elif cmd.tag == 'resolve_invalid':
        if 'slash_amount' not in cmd.args or not (isinstance(cmd.args['slash_amount'], int) and not isinstance(cmd.args['slash_amount'], bool) and 0 <= cmd.args['slash_amount'] <= 1000000):
            return StepResult(ok=False, error='invalid param slash_amount')
        if not (((cmd.args['slash_amount'] <= s.amount) and ('LOCKED' == s.status))):
            return StepResult(ok=False, error='guard failed for resolve_invalid')
        # Compute updates (simultaneous)
        new_state = State(
            amount=(s.amount - cmd.args['slash_amount']),
            min_challenge_bond=s.min_challenge_bond,
            status='SLASHED',
        )
        effects = {}
        ok, failed = check_invariants(new_state)
        if not ok:
            return StepResult(ok=False, error=f'post-invariant violated: {failed}')
        return StepResult(ok=True, state=new_state, effects=effects)
    elif cmd.tag == 'resolve_valid':
        if not (('LOCKED' == s.status)):
            return StepResult(ok=False, error='guard failed for resolve_valid')
        # Compute updates (simultaneous)
        new_state = State(
            amount=s.amount,
            min_challenge_bond=s.min_challenge_bond,
            status='ACTIVE',
        )
        effects = {}
        ok, failed = check_invariants(new_state)
        if not ok:
            return StepResult(ok=False, error=f'post-invariant violated: {failed}')
        return StepResult(ok=True, state=new_state, effects=effects)
    elif cmd.tag == 'withdraw_active':
        if not (('ACTIVE' == s.status)):
            return StepResult(ok=False, error='guard failed for withdraw_active')
        # Compute updates (simultaneous)
        new_state = State(
            amount=0,
            min_challenge_bond=s.min_challenge_bond,
            status='WITHDRAWN',
        )
        effects = {}
        ok, failed = check_invariants(new_state)
        if not ok:
            return StepResult(ok=False, error=f'post-invariant violated: {failed}')
        return StepResult(ok=True, state=new_state, effects=effects)
    elif cmd.tag == 'withdraw_remainder':
        if not (('SLASHED' == s.status)):
            return StepResult(ok=False, error='guard failed for withdraw_remainder')
        # Compute updates (simultaneous)
        new_state = State(
            amount=0,
            min_challenge_bond=s.min_challenge_bond,
            status='WITHDRAWN',
        )
        effects = {}
        ok, failed = check_invariants(new_state)
        if not ok:
            return StepResult(ok=False, error=f'post-invariant violated: {failed}')
        return StepResult(ok=True, state=new_state, effects=effects)
    else:
        return StepResult(ok=False, error=f'unknown action: {cmd.tag}')


# === Hypothesis test scaffolding ===
# Uncomment and install hypothesis to use property-based testing

# from hypothesis import given, strategies as st
# from hypothesis.stateful import RuleBasedStateMachine, rule, initialize
#
# class ModelStateMachine(RuleBasedStateMachine):
#     def __init__(self):
#         super().__init__()
#         self.state = init_state()
#
#     @initialize()
#     def init(self):
#         self.state = init_state()
#         ok, _ = check_invariants(self.state)
#         assert ok, 'init violates invariants'
#
#     # @rule()
#     # def lock_for_challenge(self, ):
#     #     cmd = Command(tag='lock_for_challenge', args={})
#     #     result = step(self.state, cmd)
#     #     if result.ok:
#     #         self.state = result.state
#
#     # @rule(slash_amount=st.integers())
#     # def resolve_invalid(self, slash_amount):
#     #     cmd = Command(tag='resolve_invalid', args={'slash_amount': slash_amount})
#     #     result = step(self.state, cmd)
#     #     if result.ok:
#     #         self.state = result.state
#
#     # @rule()
#     # def resolve_valid(self, ):
#     #     cmd = Command(tag='resolve_valid', args={})
#     #     result = step(self.state, cmd)
#     #     if result.ok:
#     #         self.state = result.state
#
#     # @rule()
#     # def withdraw_active(self, ):
#     #     cmd = Command(tag='withdraw_active', args={})
#     #     result = step(self.state, cmd)
#     #     if result.ok:
#     #         self.state = result.state
#
#     # @rule()
#     # def withdraw_remainder(self, ):
#     #     cmd = Command(tag='withdraw_remainder', args={})
#     #     result = step(self.state, cmd)
#     #     if result.ok:
#     #         self.state = result.state
#
# TestModel = ModelStateMachine.TestCase


def replay_trace(commands: list[tuple[str, dict[str, Any]]]) -> list[StepResult]:
    """Replay a trace of commands and return results."""
    results: list[StepResult] = []
    s = init_state()
    for tag, args in commands:
        cmd = Command(tag=tag, args=args)
        result = step(s, cmd)
        results.append(result)
        if result.ok and result.state is not None:
            s = result.state
        else:
            break
    return results


if __name__ == '__main__':
    # Quick sanity check
    s0 = init_state()
    ok, failed = check_invariants(s0)
    print(f'Initial state: {s0}')
    print(f'Invariants OK: {ok}')
    if not ok:
        print(f'  Failed: {failed}')
