"""
Auto-generated Python reference model for: ian.fraud_proof
IR hash: sha256:298a4fc18c13615bcb7f129e8e255439c5324c07f287d9799d536f78c42dfb40

Generated by ESSO (Evolutionary Spec Search Optimizer)

This file is standalone and has no ESSO dependencies.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Literal, Mapping


# Domain enums
REASON_SYMBOLS = ('NONE', 'INVALID_SIG', 'STATE_MATCH', 'EXPIRED')
REJECTION_REASON_SYMBOLS = ('NONE', 'INVALID_SIG', 'STATE_MATCH', 'EXPIRED')
STATUS_SYMBOLS = ('CREATED', 'SUBMITTED', 'VERIFIED', 'REJECTED')


@dataclass(frozen=True)
class State:
    """Model state."""
    rejection_reason: str
    status: str


@dataclass(frozen=True)
class Command:
    """Command to execute."""
    tag: Literal('submit', 'verify_invalid', 'verify_valid')
    args: Mapping[str, Any]


@dataclass(frozen=True)
class StepResult:
    """Result of a step execution."""
    ok: bool
    state: State | None = None
    effects: Mapping[str, Any] | None = None
    error: str | None = None


def init_state() -> State:
    """Return the initial state."""
    return State(
        rejection_reason='NONE',
        status='CREATED',
    )


def check_invariants(s: State) -> tuple[bool, str | None]:
    """Check all invariants. Returns (ok, first_failed_id)."""
    if not (s.rejection_reason in ('NONE', 'INVALID_SIG', 'STATE_MATCH', 'EXPIRED')):
        return False, 'domain_rejection_reason'
    if not (s.status in ('CREATED', 'SUBMITTED', 'VERIFIED', 'REJECTED')):
        return False, 'domain_status'
    if not ((('NONE' == s.rejection_reason) or (('CREATED' != s.status) and ('SUBMITTED' != s.status)))):
        return False, 'pending_no_reason'
    if not ((('NONE' != s.rejection_reason) or ('REJECTED' != s.status))):
        return False, 'rejected_has_reason'
    if not ((('VERIFIED' != s.status) or ('NONE' == s.rejection_reason))):
        return False, 'verified_no_reason'
    return True, None


def step(s: State, cmd: Command) -> StepResult:
    """Execute a step. Returns StepResult."""
    # Check pre-state invariants
    ok, failed = check_invariants(s)
    if not ok:
        return StepResult(ok=False, error=f'pre-invariant violated: {failed}')

    if cmd.tag == 'submit':
        if not (('CREATED' == s.status)):
            return StepResult(ok=False, error='guard failed for submit')
        # Compute updates (simultaneous)
        new_state = State(
            rejection_reason=s.rejection_reason,
            status='SUBMITTED',
        )
        effects = {}
        ok, failed = check_invariants(new_state)
        if not ok:
            return StepResult(ok=False, error=f'post-invariant violated: {failed}')
        return StepResult(ok=True, state=new_state, effects=effects)
    elif cmd.tag == 'verify_invalid':
        if 'reason' not in cmd.args or not (cmd.args['reason'] in ('NONE', 'INVALID_SIG', 'STATE_MATCH', 'EXPIRED')):
            return StepResult(ok=False, error='invalid param reason')
        if not ((('NONE' != cmd.args['reason']) and ('SUBMITTED' == s.status))):
            return StepResult(ok=False, error='guard failed for verify_invalid')
        # Compute updates (simultaneous)
        new_state = State(
            rejection_reason=cmd.args['reason'],
            status='REJECTED',
        )
        effects = {}
        ok, failed = check_invariants(new_state)
        if not ok:
            return StepResult(ok=False, error=f'post-invariant violated: {failed}')
        return StepResult(ok=True, state=new_state, effects=effects)
    elif cmd.tag == 'verify_valid':
        if not (('SUBMITTED' == s.status)):
            return StepResult(ok=False, error='guard failed for verify_valid')
        # Compute updates (simultaneous)
        new_state = State(
            rejection_reason=s.rejection_reason,
            status='VERIFIED',
        )
        effects = {}
        ok, failed = check_invariants(new_state)
        if not ok:
            return StepResult(ok=False, error=f'post-invariant violated: {failed}')
        return StepResult(ok=True, state=new_state, effects=effects)
    else:
        return StepResult(ok=False, error=f'unknown action: {cmd.tag}')


# === Hypothesis test scaffolding ===
# Uncomment and install hypothesis to use property-based testing

# from hypothesis import given, strategies as st
# from hypothesis.stateful import RuleBasedStateMachine, rule, initialize
#
# class ModelStateMachine(RuleBasedStateMachine):
#     def __init__(self):
#         super().__init__()
#         self.state = init_state()
#
#     @initialize()
#     def init(self):
#         self.state = init_state()
#         ok, _ = check_invariants(self.state)
#         assert ok, 'init violates invariants'
#
#     # @rule()
#     # def submit(self, ):
#     #     cmd = Command(tag='submit', args={})
#     #     result = step(self.state, cmd)
#     #     if result.ok:
#     #         self.state = result.state
#
#     # @rule(reason=st.integers())
#     # def verify_invalid(self, reason):
#     #     cmd = Command(tag='verify_invalid', args={'reason': reason})
#     #     result = step(self.state, cmd)
#     #     if result.ok:
#     #         self.state = result.state
#
#     # @rule()
#     # def verify_valid(self, ):
#     #     cmd = Command(tag='verify_valid', args={})
#     #     result = step(self.state, cmd)
#     #     if result.ok:
#     #         self.state = result.state
#
# TestModel = ModelStateMachine.TestCase


def replay_trace(commands: list[tuple[str, dict[str, Any]]]) -> list[StepResult]:
    """Replay a trace of commands and return results."""
    results: list[StepResult] = []
    s = init_state()
    for tag, args in commands:
        cmd = Command(tag=tag, args=args)
        result = step(s, cmd)
        results.append(result)
        if result.ok and result.state is not None:
            s = result.state
        else:
            break
    return results


if __name__ == '__main__':
    # Quick sanity check
    s0 = init_state()
    ok, failed = check_invariants(s0)
    print(f'Initial state: {s0}')
    print(f'Invariants OK: {ok}')
    if not ok:
        print(f'  Failed: {failed}')
