"""
Auto-generated Python reference model for: peer_state_fsm
IR hash: sha256:ff741b6b32e8033c221784e0908aeb08ec29b0669d943ef3256cf762bc6d99d4

Generated by ESSO (Evolutionary Spec Search Optimizer)

This file is standalone and has no ESSO dependencies.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Literal, Mapping


# Domain enums
STATE_SYMBOLS = ('CONNECTING', 'CONNECTED', 'HANDSHAKING', 'READY', 'DISCONNECTING', 'DISCONNECTED')


@dataclass(frozen=True)
class State:
    """Model state."""
    handshake_completed: bool
    is_verified: bool
    state: str


@dataclass(frozen=True)
class Command:
    """Command to execute."""
    tag: Literal('complete_handshake', 'connect', 'disconnect_from_connected', 'disconnect_from_connecting', 'disconnect_from_handshaking', 'disconnect_from_ready', 'finalize_disconnect', 'start_handshake')
    args: Mapping[str, Any]


@dataclass(frozen=True)
class StepResult:
    """Result of a step execution."""
    ok: bool
    state: State | None = None
    effects: Mapping[str, Any] | None = None
    error: str | None = None


def init_state() -> State:
    """Return the initial state."""
    return State(
        handshake_completed=False,
        is_verified=False,
        state='CONNECTING',
    )


def check_invariants(s: State) -> tuple[bool, str | None]:
    """Check all invariants. Returns (ok, first_failed_id)."""
    if not (isinstance(s.handshake_completed, bool)):
        return False, 'domain_handshake_completed'
    if not (isinstance(s.is_verified, bool)):
        return False, 'domain_is_verified'
    if not (s.state in ('CONNECTING', 'CONNECTED', 'HANDSHAKING', 'READY', 'DISCONNECTING', 'DISCONNECTED')):
        return False, 'domain_state'
    if not (((not ('DISCONNECTED' == s.state)) or True)):
        return False, 'disconnected_is_terminal'
    if not (((not ('READY' == s.state)) or s.handshake_completed)):
        return False, 'ready_requires_handshake'
    if not (((not ('READY' == s.state)) or s.is_verified)):
        return False, 'ready_requires_verified'
    return True, None


def step(s: State, cmd: Command) -> StepResult:
    """Execute a step. Returns StepResult."""
    # Check pre-state invariants
    ok, failed = check_invariants(s)
    if not ok:
        return StepResult(ok=False, error=f'pre-invariant violated: {failed}')

    if cmd.tag == 'complete_handshake':
        if not (('HANDSHAKING' == s.state)):
            return StepResult(ok=False, error='guard failed for complete_handshake')
        # Compute updates (simultaneous)
        new_state = State(
            handshake_completed=True,
            is_verified=True,
            state='READY',
        )
        effects = {
            'transition_valid': True,
        }
        ok, failed = check_invariants(new_state)
        if not ok:
            return StepResult(ok=False, error=f'post-invariant violated: {failed}')
        return StepResult(ok=True, state=new_state, effects=effects)
    elif cmd.tag == 'connect':
        if not (('CONNECTING' == s.state)):
            return StepResult(ok=False, error='guard failed for connect')
        # Compute updates (simultaneous)
        new_state = State(
            handshake_completed=s.handshake_completed,
            is_verified=s.is_verified,
            state='CONNECTED',
        )
        effects = {
            'transition_valid': True,
        }
        ok, failed = check_invariants(new_state)
        if not ok:
            return StepResult(ok=False, error=f'post-invariant violated: {failed}')
        return StepResult(ok=True, state=new_state, effects=effects)
    elif cmd.tag == 'disconnect_from_connected':
        if not (('CONNECTED' == s.state)):
            return StepResult(ok=False, error='guard failed for disconnect_from_connected')
        # Compute updates (simultaneous)
        new_state = State(
            handshake_completed=s.handshake_completed,
            is_verified=s.is_verified,
            state='DISCONNECTING',
        )
        effects = {
            'transition_valid': True,
        }
        ok, failed = check_invariants(new_state)
        if not ok:
            return StepResult(ok=False, error=f'post-invariant violated: {failed}')
        return StepResult(ok=True, state=new_state, effects=effects)
    elif cmd.tag == 'disconnect_from_connecting':
        if not (('CONNECTING' == s.state)):
            return StepResult(ok=False, error='guard failed for disconnect_from_connecting')
        # Compute updates (simultaneous)
        new_state = State(
            handshake_completed=s.handshake_completed,
            is_verified=s.is_verified,
            state='DISCONNECTING',
        )
        effects = {
            'transition_valid': True,
        }
        ok, failed = check_invariants(new_state)
        if not ok:
            return StepResult(ok=False, error=f'post-invariant violated: {failed}')
        return StepResult(ok=True, state=new_state, effects=effects)
    elif cmd.tag == 'disconnect_from_handshaking':
        if not (('HANDSHAKING' == s.state)):
            return StepResult(ok=False, error='guard failed for disconnect_from_handshaking')
        # Compute updates (simultaneous)
        new_state = State(
            handshake_completed=s.handshake_completed,
            is_verified=s.is_verified,
            state='DISCONNECTING',
        )
        effects = {
            'transition_valid': True,
        }
        ok, failed = check_invariants(new_state)
        if not ok:
            return StepResult(ok=False, error=f'post-invariant violated: {failed}')
        return StepResult(ok=True, state=new_state, effects=effects)
    elif cmd.tag == 'disconnect_from_ready':
        if not (('READY' == s.state)):
            return StepResult(ok=False, error='guard failed for disconnect_from_ready')
        # Compute updates (simultaneous)
        new_state = State(
            handshake_completed=s.handshake_completed,
            is_verified=s.is_verified,
            state='DISCONNECTING',
        )
        effects = {
            'transition_valid': True,
        }
        ok, failed = check_invariants(new_state)
        if not ok:
            return StepResult(ok=False, error=f'post-invariant violated: {failed}')
        return StepResult(ok=True, state=new_state, effects=effects)
    elif cmd.tag == 'finalize_disconnect':
        if not (('DISCONNECTING' == s.state)):
            return StepResult(ok=False, error='guard failed for finalize_disconnect')
        # Compute updates (simultaneous)
        new_state = State(
            handshake_completed=s.handshake_completed,
            is_verified=s.is_verified,
            state='DISCONNECTED',
        )
        effects = {
            'transition_valid': True,
        }
        ok, failed = check_invariants(new_state)
        if not ok:
            return StepResult(ok=False, error=f'post-invariant violated: {failed}')
        return StepResult(ok=True, state=new_state, effects=effects)
    elif cmd.tag == 'start_handshake':
        if not (('CONNECTED' == s.state)):
            return StepResult(ok=False, error='guard failed for start_handshake')
        # Compute updates (simultaneous)
        new_state = State(
            handshake_completed=s.handshake_completed,
            is_verified=s.is_verified,
            state='HANDSHAKING',
        )
        effects = {
            'transition_valid': True,
        }
        ok, failed = check_invariants(new_state)
        if not ok:
            return StepResult(ok=False, error=f'post-invariant violated: {failed}')
        return StepResult(ok=True, state=new_state, effects=effects)
    else:
        return StepResult(ok=False, error=f'unknown action: {cmd.tag}')


# === Hypothesis test scaffolding ===
# Uncomment and install hypothesis to use property-based testing

# from hypothesis import given, strategies as st
# from hypothesis.stateful import RuleBasedStateMachine, rule, initialize
#
# class ModelStateMachine(RuleBasedStateMachine):
#     def __init__(self):
#         super().__init__()
#         self.state = init_state()
#
#     @initialize()
#     def init(self):
#         self.state = init_state()
#         ok, _ = check_invariants(self.state)
#         assert ok, 'init violates invariants'
#
#     # @rule()
#     # def complete_handshake(self, ):
#     #     cmd = Command(tag='complete_handshake', args={})
#     #     result = step(self.state, cmd)
#     #     if result.ok:
#     #         self.state = result.state
#
#     # @rule()
#     # def connect(self, ):
#     #     cmd = Command(tag='connect', args={})
#     #     result = step(self.state, cmd)
#     #     if result.ok:
#     #         self.state = result.state
#
#     # @rule()
#     # def disconnect_from_connected(self, ):
#     #     cmd = Command(tag='disconnect_from_connected', args={})
#     #     result = step(self.state, cmd)
#     #     if result.ok:
#     #         self.state = result.state
#
#     # @rule()
#     # def disconnect_from_connecting(self, ):
#     #     cmd = Command(tag='disconnect_from_connecting', args={})
#     #     result = step(self.state, cmd)
#     #     if result.ok:
#     #         self.state = result.state
#
#     # @rule()
#     # def disconnect_from_handshaking(self, ):
#     #     cmd = Command(tag='disconnect_from_handshaking', args={})
#     #     result = step(self.state, cmd)
#     #     if result.ok:
#     #         self.state = result.state
#
#     # @rule()
#     # def disconnect_from_ready(self, ):
#     #     cmd = Command(tag='disconnect_from_ready', args={})
#     #     result = step(self.state, cmd)
#     #     if result.ok:
#     #         self.state = result.state
#
#     # @rule()
#     # def finalize_disconnect(self, ):
#     #     cmd = Command(tag='finalize_disconnect', args={})
#     #     result = step(self.state, cmd)
#     #     if result.ok:
#     #         self.state = result.state
#
#     # @rule()
#     # def start_handshake(self, ):
#     #     cmd = Command(tag='start_handshake', args={})
#     #     result = step(self.state, cmd)
#     #     if result.ok:
#     #         self.state = result.state
#
# TestModel = ModelStateMachine.TestCase


def replay_trace(commands: list[tuple[str, dict[str, Any]]]) -> list[StepResult]:
    """Replay a trace of commands and return results."""
    results: list[StepResult] = []
    s = init_state()
    for tag, args in commands:
        cmd = Command(tag=tag, args=args)
        result = step(s, cmd)
        results.append(result)
        if result.ok and result.state is not None:
            s = result.state
        else:
            break
    return results


if __name__ == '__main__':
    # Quick sanity check
    s0 = init_state()
    ok, failed = check_invariants(s0)
    print(f'Initial state: {s0}')
    print(f'Invariants OK: {ok}')
    if not ok:
        print(f'  Failed: {failed}')
