"""
Auto-generated Python reference model for: priority_queue_kernel
IR hash: sha256:f0e7bb5f1134032702b84cdbeb251606a3c78c62ea923d5c6d1d21d1b05a568a

Generated by ESSO (Evolutionary Spec Search Optimizer)

This file is standalone and has no ESSO dependencies.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Literal, Mapping


@dataclass(frozen=True)
class State:
    """Model state."""
    capacity: int
    count: int
    head_priority: int
    is_empty: bool
    is_full: bool


@dataclass(frozen=True)
class Command:
    """Command to execute."""
    tag: Literal('clear', 'extract', 'insert')
    args: Mapping[str, Any]


@dataclass(frozen=True)
class StepResult:
    """Result of a step execution."""
    ok: bool
    state: State | None = None
    effects: Mapping[str, Any] | None = None
    error: str | None = None


def init_state() -> State:
    """Return the initial state."""
    return State(
        capacity=50,
        count=0,
        head_priority=0,
        is_empty=True,
        is_full=False,
    )


def check_invariants(s: State) -> tuple[bool, str | None]:
    """Check all invariants. Returns (ok, first_failed_id)."""
    if not (isinstance(s.capacity, int) and not isinstance(s.capacity, bool) and 1 <= s.capacity <= 100):
        return False, 'domain_capacity'
    if not (isinstance(s.count, int) and not isinstance(s.count, bool) and 0 <= s.count <= 100):
        return False, 'domain_count'
    if not (isinstance(s.head_priority, int) and not isinstance(s.head_priority, bool) and 0 <= s.head_priority <= 100):
        return False, 'domain_head_priority'
    if not (isinstance(s.is_empty, bool)):
        return False, 'domain_is_empty'
    if not (isinstance(s.is_full, bool)):
        return False, 'domain_is_full'
    if not ((s.count <= s.capacity)):
        return False, 'count_bounded'
    if not ((s.count >= 0)):
        return False, 'count_non_negative'
    if not (((True == s.is_empty) == (0 == s.count))):
        return False, 'empty_iff_zero'
    if not (((True == s.is_full) == (s.capacity == s.count))):
        return False, 'full_iff_capacity'
    return True, None


def step(s: State, cmd: Command) -> StepResult:
    """Execute a step. Returns StepResult."""
    # Check pre-state invariants
    ok, failed = check_invariants(s)
    if not ok:
        return StepResult(ok=False, error=f'pre-invariant violated: {failed}')

    if cmd.tag == 'clear':
        if not ((s.count > 0)):
            return StepResult(ok=False, error='guard failed for clear')
        # Compute updates (simultaneous)
        new_state = State(
            capacity=s.capacity,
            count=0,
            head_priority=0,
            is_empty=True,
            is_full=False,
        )
        effects = {
            'event': 'CLEAR',
        }
        ok, failed = check_invariants(new_state)
        if not ok:
            return StepResult(ok=False, error=f'post-invariant violated: {failed}')
        return StepResult(ok=True, state=new_state, effects=effects)
    elif cmd.tag == 'extract':
        if not ((s.count > 0)):
            return StepResult(ok=False, error='guard failed for extract')
        # Compute updates (simultaneous)
        new_state = State(
            capacity=s.capacity,
            count=(s.count - 1),
            head_priority=s.head_priority,
            is_empty=(0 == (s.count - 1)),
            is_full=False,
        )
        effects = {
            'event': 'EXTRACT',
        }
        ok, failed = check_invariants(new_state)
        if not ok:
            return StepResult(ok=False, error=f'post-invariant violated: {failed}')
        return StepResult(ok=True, state=new_state, effects=effects)
    elif cmd.tag == 'insert':
        if not ((s.count < s.capacity)):
            return StepResult(ok=False, error='guard failed for insert')
        # Compute updates (simultaneous)
        new_state = State(
            capacity=s.capacity,
            count=(1 + s.count),
            head_priority=s.head_priority,
            is_empty=False,
            is_full=((1 + s.count) == s.capacity),
        )
        effects = {
            'event': 'INSERT',
        }
        ok, failed = check_invariants(new_state)
        if not ok:
            return StepResult(ok=False, error=f'post-invariant violated: {failed}')
        return StepResult(ok=True, state=new_state, effects=effects)
    else:
        return StepResult(ok=False, error=f'unknown action: {cmd.tag}')


# === Hypothesis test scaffolding ===
# Uncomment and install hypothesis to use property-based testing

# from hypothesis import given, strategies as st
# from hypothesis.stateful import RuleBasedStateMachine, rule, initialize
#
# class ModelStateMachine(RuleBasedStateMachine):
#     def __init__(self):
#         super().__init__()
#         self.state = init_state()
#
#     @initialize()
#     def init(self):
#         self.state = init_state()
#         ok, _ = check_invariants(self.state)
#         assert ok, 'init violates invariants'
#
#     # @rule()
#     # def clear(self, ):
#     #     cmd = Command(tag='clear', args={})
#     #     result = step(self.state, cmd)
#     #     if result.ok:
#     #         self.state = result.state
#
#     # @rule()
#     # def extract(self, ):
#     #     cmd = Command(tag='extract', args={})
#     #     result = step(self.state, cmd)
#     #     if result.ok:
#     #         self.state = result.state
#
#     # @rule()
#     # def insert(self, ):
#     #     cmd = Command(tag='insert', args={})
#     #     result = step(self.state, cmd)
#     #     if result.ok:
#     #         self.state = result.state
#
# TestModel = ModelStateMachine.TestCase


def replay_trace(commands: list[tuple[str, dict[str, Any]]]) -> list[StepResult]:
    """Replay a trace of commands and return results."""
    results: list[StepResult] = []
    s = init_state()
    for tag, args in commands:
        cmd = Command(tag=tag, args=args)
        result = step(s, cmd)
        results.append(result)
        if result.ok and result.state is not None:
            s = result.state
        else:
            break
    return results


if __name__ == '__main__':
    # Quick sanity check
    s0 = init_state()
    ok, failed = check_invariants(s0)
    print(f'Initial state: {s0}')
    print(f'Invariants OK: {ok}')
    if not ok:
        print(f'  Failed: {failed}')
