"""
Auto-generated Python reference model for: rate_limiter
IR hash: sha256:4fdfd80b9ef67570c25c38fb5afa4a04c1907bee4ce0f41a6ae584ea34e99a2d

Generated by ESSO (Evolutionary Spec Search Optimizer)

This file is standalone and has no ESSO dependencies.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Literal, Mapping


@dataclass(frozen=True)
class State:
    """Model state."""
    burst: int
    tokens: int


@dataclass(frozen=True)
class Command:
    """Command to execute."""
    tag: Literal('acquire_fail', 'acquire_success', 'replenish_one', 'reset')
    args: Mapping[str, Any]


@dataclass(frozen=True)
class StepResult:
    """Result of a step execution."""
    ok: bool
    state: State | None = None
    effects: Mapping[str, Any] | None = None
    error: str | None = None


def init_state() -> State:
    """Return the initial state."""
    return State(
        burst=20,
        tokens=20,
    )


def check_invariants(s: State) -> tuple[bool, str | None]:
    """Check all invariants. Returns (ok, first_failed_id)."""
    if not (isinstance(s.burst, int) and not isinstance(s.burst, bool) and 1 <= s.burst <= 20):
        return False, 'domain_burst'
    if not (isinstance(s.tokens, int) and not isinstance(s.tokens, bool) and 0 <= s.tokens <= 20):
        return False, 'domain_tokens'
    if not ((s.tokens <= s.burst)):
        return False, 'tokens_bounded_by_burst'
    if not ((s.tokens >= 0)):
        return False, 'tokens_non_negative'
    return True, None


def step(s: State, cmd: Command) -> StepResult:
    """Execute a step. Returns StepResult."""
    # Check pre-state invariants
    ok, failed = check_invariants(s)
    if not ok:
        return StepResult(ok=False, error=f'pre-invariant violated: {failed}')

    if cmd.tag == 'acquire_fail':
        if not ((s.tokens < 1)):
            return StepResult(ok=False, error='guard failed for acquire_fail')
        # Compute updates (simultaneous)
        new_state = State(
            burst=s.burst,
            tokens=s.tokens,
        )
        effects = {
            'allowed': False,
        }
        ok, failed = check_invariants(new_state)
        if not ok:
            return StepResult(ok=False, error=f'post-invariant violated: {failed}')
        return StepResult(ok=True, state=new_state, effects=effects)
    elif cmd.tag == 'acquire_success':
        if not ((s.tokens >= 1)):
            return StepResult(ok=False, error='guard failed for acquire_success')
        # Compute updates (simultaneous)
        new_state = State(
            burst=s.burst,
            tokens=(s.tokens - 1),
        )
        effects = {
            'allowed': True,
        }
        ok, failed = check_invariants(new_state)
        if not ok:
            return StepResult(ok=False, error=f'post-invariant violated: {failed}')
        return StepResult(ok=True, state=new_state, effects=effects)
    elif cmd.tag == 'replenish_one':
        if not ((s.tokens < s.burst)):
            return StepResult(ok=False, error='guard failed for replenish_one')
        # Compute updates (simultaneous)
        new_state = State(
            burst=s.burst,
            tokens=(1 + s.tokens),
        )
        effects = {
            'allowed': True,
        }
        ok, failed = check_invariants(new_state)
        if not ok:
            return StepResult(ok=False, error=f'post-invariant violated: {failed}')
        return StepResult(ok=True, state=new_state, effects=effects)
    elif cmd.tag == 'reset':
        if not (True):
            return StepResult(ok=False, error='guard failed for reset')
        # Compute updates (simultaneous)
        new_state = State(
            burst=s.burst,
            tokens=s.burst,
        )
        effects = {
            'allowed': True,
        }
        ok, failed = check_invariants(new_state)
        if not ok:
            return StepResult(ok=False, error=f'post-invariant violated: {failed}')
        return StepResult(ok=True, state=new_state, effects=effects)
    else:
        return StepResult(ok=False, error=f'unknown action: {cmd.tag}')


# === Hypothesis test scaffolding ===
# Uncomment and install hypothesis to use property-based testing

# from hypothesis import given, strategies as st
# from hypothesis.stateful import RuleBasedStateMachine, rule, initialize
#
# class ModelStateMachine(RuleBasedStateMachine):
#     def __init__(self):
#         super().__init__()
#         self.state = init_state()
#
#     @initialize()
#     def init(self):
#         self.state = init_state()
#         ok, _ = check_invariants(self.state)
#         assert ok, 'init violates invariants'
#
#     # @rule()
#     # def acquire_fail(self, ):
#     #     cmd = Command(tag='acquire_fail', args={})
#     #     result = step(self.state, cmd)
#     #     if result.ok:
#     #         self.state = result.state
#
#     # @rule()
#     # def acquire_success(self, ):
#     #     cmd = Command(tag='acquire_success', args={})
#     #     result = step(self.state, cmd)
#     #     if result.ok:
#     #         self.state = result.state
#
#     # @rule()
#     # def replenish_one(self, ):
#     #     cmd = Command(tag='replenish_one', args={})
#     #     result = step(self.state, cmd)
#     #     if result.ok:
#     #         self.state = result.state
#
#     # @rule()
#     # def reset(self, ):
#     #     cmd = Command(tag='reset', args={})
#     #     result = step(self.state, cmd)
#     #     if result.ok:
#     #         self.state = result.state
#
# TestModel = ModelStateMachine.TestCase


def replay_trace(commands: list[tuple[str, dict[str, Any]]]) -> list[StepResult]:
    """Replay a trace of commands and return results."""
    results: list[StepResult] = []
    s = init_state()
    for tag, args in commands:
        cmd = Command(tag=tag, args=args)
        result = step(s, cmd)
        results.append(result)
        if result.ok and result.state is not None:
            s = result.state
        else:
            break
    return results


if __name__ == '__main__':
    # Quick sanity check
    s0 = init_state()
    ok, failed = check_invariants(s0)
    print(f'Initial state: {s0}')
    print(f'Invariants OK: {ok}')
    if not ok:
        print(f'  Failed: {failed}')
