"""
Auto-generated Python reference model for: slot_state_fsm
IR hash: sha256:54a184f4bad206341a67286771713bbced3ace6d908491d519b7cd961a842451

Generated by ESSO (Evolutionary Spec Search Optimizer)

This file is standalone and has no ESSO dependencies.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Literal, Mapping


# Domain enums
STATE_SYMBOLS = ('COLLECTING', 'ORDERING', 'COMMITTED', 'EXECUTED', 'CANCELLED')


@dataclass(frozen=True)
class State:
    """Model state."""
    contribution_count: int
    has_ordered_ids: bool
    has_vrf: bool
    state: str


@dataclass(frozen=True)
class Command:
    """Command to execute."""
    tag: Literal('add_contribution', 'cancel_collecting', 'cancel_committed', 'cancel_ordering', 'commit_empty_slot', 'compute_vrf_and_commit', 'execute_slot', 'start_ordering')
    args: Mapping[str, Any]


@dataclass(frozen=True)
class StepResult:
    """Result of a step execution."""
    ok: bool
    state: State | None = None
    effects: Mapping[str, Any] | None = None
    error: str | None = None


def init_state() -> State:
    """Return the initial state."""
    return State(
        contribution_count=0,
        has_ordered_ids=False,
        has_vrf=False,
        state='COLLECTING',
    )


def check_invariants(s: State) -> tuple[bool, str | None]:
    """Check all invariants. Returns (ok, first_failed_id)."""
    if not (isinstance(s.contribution_count, int) and not isinstance(s.contribution_count, bool) and 0 <= s.contribution_count <= 1000):
        return False, 'domain_contribution_count'
    if not (isinstance(s.has_ordered_ids, bool)):
        return False, 'domain_has_ordered_ids'
    if not (isinstance(s.has_vrf, bool)):
        return False, 'domain_has_vrf'
    if not (s.state in ('COLLECTING', 'ORDERING', 'COMMITTED', 'EXECUTED', 'CANCELLED')):
        return False, 'domain_state'
    if not (((not ('COMMITTED' == s.state)) or (True == s.has_vrf))):
        return False, 'committed_has_vrf'
    if not (((not ('EXECUTED' == s.state)) or (True == s.has_ordered_ids))):
        return False, 'executed_has_ordered'
    if not (((not ('COLLECTING' != s.state)) or (s.contribution_count == s.contribution_count))):
        return False, 'ordering_not_accepting'
    return True, None


def step(s: State, cmd: Command) -> StepResult:
    """Execute a step. Returns StepResult."""
    # Check pre-state invariants
    ok, failed = check_invariants(s)
    if not ok:
        return StepResult(ok=False, error=f'pre-invariant violated: {failed}')

    if cmd.tag == 'add_contribution':
        if not (((s.contribution_count < 1000) and ('COLLECTING' == s.state))):
            return StepResult(ok=False, error='guard failed for add_contribution')
        # Compute updates (simultaneous)
        new_state = State(
            contribution_count=(1 + s.contribution_count),
            has_ordered_ids=s.has_ordered_ids,
            has_vrf=s.has_vrf,
            state=s.state,
        )
        effects = {
            'event': 'SLOT_TIMEOUT',
        }
        ok, failed = check_invariants(new_state)
        if not ok:
            return StepResult(ok=False, error=f'post-invariant violated: {failed}')
        return StepResult(ok=True, state=new_state, effects=effects)
    elif cmd.tag == 'cancel_collecting':
        if not (('COLLECTING' == s.state)):
            return StepResult(ok=False, error='guard failed for cancel_collecting')
        # Compute updates (simultaneous)
        new_state = State(
            contribution_count=s.contribution_count,
            has_ordered_ids=s.has_ordered_ids,
            has_vrf=s.has_vrf,
            state='CANCELLED',
        )
        effects = {
            'event': 'CANCEL',
        }
        ok, failed = check_invariants(new_state)
        if not ok:
            return StepResult(ok=False, error=f'post-invariant violated: {failed}')
        return StepResult(ok=True, state=new_state, effects=effects)
    elif cmd.tag == 'cancel_committed':
        if not (('COMMITTED' == s.state)):
            return StepResult(ok=False, error='guard failed for cancel_committed')
        # Compute updates (simultaneous)
        new_state = State(
            contribution_count=s.contribution_count,
            has_ordered_ids=s.has_ordered_ids,
            has_vrf=s.has_vrf,
            state='CANCELLED',
        )
        effects = {
            'event': 'CANCEL',
        }
        ok, failed = check_invariants(new_state)
        if not ok:
            return StepResult(ok=False, error=f'post-invariant violated: {failed}')
        return StepResult(ok=True, state=new_state, effects=effects)
    elif cmd.tag == 'cancel_ordering':
        if not (('ORDERING' == s.state)):
            return StepResult(ok=False, error='guard failed for cancel_ordering')
        # Compute updates (simultaneous)
        new_state = State(
            contribution_count=s.contribution_count,
            has_ordered_ids=s.has_ordered_ids,
            has_vrf=s.has_vrf,
            state='CANCELLED',
        )
        effects = {
            'event': 'CANCEL',
        }
        ok, failed = check_invariants(new_state)
        if not ok:
            return StepResult(ok=False, error=f'post-invariant violated: {failed}')
        return StepResult(ok=True, state=new_state, effects=effects)
    elif cmd.tag == 'commit_empty_slot':
        if not (((0 == s.contribution_count) and ('ORDERING' == s.state))):
            return StepResult(ok=False, error='guard failed for commit_empty_slot')
        # Compute updates (simultaneous)
        new_state = State(
            contribution_count=s.contribution_count,
            has_ordered_ids=True,
            has_vrf=True,
            state='COMMITTED',
        )
        effects = {
            'event': 'ORDER_COMMITTED',
        }
        ok, failed = check_invariants(new_state)
        if not ok:
            return StepResult(ok=False, error=f'post-invariant violated: {failed}')
        return StepResult(ok=True, state=new_state, effects=effects)
    elif cmd.tag == 'compute_vrf_and_commit':
        if not ((('ORDERING' == s.state) and (s.contribution_count > 0))):
            return StepResult(ok=False, error='guard failed for compute_vrf_and_commit')
        # Compute updates (simultaneous)
        new_state = State(
            contribution_count=s.contribution_count,
            has_ordered_ids=True,
            has_vrf=True,
            state='COMMITTED',
        )
        effects = {
            'event': 'VRF_COMPUTED',
        }
        ok, failed = check_invariants(new_state)
        if not ok:
            return StepResult(ok=False, error=f'post-invariant violated: {failed}')
        return StepResult(ok=True, state=new_state, effects=effects)
    elif cmd.tag == 'execute_slot':
        if not (((True == s.has_ordered_ids) and ('COMMITTED' == s.state))):
            return StepResult(ok=False, error='guard failed for execute_slot')
        # Compute updates (simultaneous)
        new_state = State(
            contribution_count=s.contribution_count,
            has_ordered_ids=s.has_ordered_ids,
            has_vrf=s.has_vrf,
            state='EXECUTED',
        )
        effects = {
            'event': 'EXECUTE',
        }
        ok, failed = check_invariants(new_state)
        if not ok:
            return StepResult(ok=False, error=f'post-invariant violated: {failed}')
        return StepResult(ok=True, state=new_state, effects=effects)
    elif cmd.tag == 'start_ordering':
        if not (('COLLECTING' == s.state)):
            return StepResult(ok=False, error='guard failed for start_ordering')
        # Compute updates (simultaneous)
        new_state = State(
            contribution_count=s.contribution_count,
            has_ordered_ids=s.has_ordered_ids,
            has_vrf=s.has_vrf,
            state='ORDERING',
        )
        effects = {
            'event': 'SLOT_TIMEOUT',
        }
        ok, failed = check_invariants(new_state)
        if not ok:
            return StepResult(ok=False, error=f'post-invariant violated: {failed}')
        return StepResult(ok=True, state=new_state, effects=effects)
    else:
        return StepResult(ok=False, error=f'unknown action: {cmd.tag}')


# === Hypothesis test scaffolding ===
# Uncomment and install hypothesis to use property-based testing

# from hypothesis import given, strategies as st
# from hypothesis.stateful import RuleBasedStateMachine, rule, initialize
#
# class ModelStateMachine(RuleBasedStateMachine):
#     def __init__(self):
#         super().__init__()
#         self.state = init_state()
#
#     @initialize()
#     def init(self):
#         self.state = init_state()
#         ok, _ = check_invariants(self.state)
#         assert ok, 'init violates invariants'
#
#     # @rule()
#     # def add_contribution(self, ):
#     #     cmd = Command(tag='add_contribution', args={})
#     #     result = step(self.state, cmd)
#     #     if result.ok:
#     #         self.state = result.state
#
#     # @rule()
#     # def cancel_collecting(self, ):
#     #     cmd = Command(tag='cancel_collecting', args={})
#     #     result = step(self.state, cmd)
#     #     if result.ok:
#     #         self.state = result.state
#
#     # @rule()
#     # def cancel_committed(self, ):
#     #     cmd = Command(tag='cancel_committed', args={})
#     #     result = step(self.state, cmd)
#     #     if result.ok:
#     #         self.state = result.state
#
#     # @rule()
#     # def cancel_ordering(self, ):
#     #     cmd = Command(tag='cancel_ordering', args={})
#     #     result = step(self.state, cmd)
#     #     if result.ok:
#     #         self.state = result.state
#
#     # @rule()
#     # def commit_empty_slot(self, ):
#     #     cmd = Command(tag='commit_empty_slot', args={})
#     #     result = step(self.state, cmd)
#     #     if result.ok:
#     #         self.state = result.state
#
#     # @rule()
#     # def compute_vrf_and_commit(self, ):
#     #     cmd = Command(tag='compute_vrf_and_commit', args={})
#     #     result = step(self.state, cmd)
#     #     if result.ok:
#     #         self.state = result.state
#
#     # @rule()
#     # def execute_slot(self, ):
#     #     cmd = Command(tag='execute_slot', args={})
#     #     result = step(self.state, cmd)
#     #     if result.ok:
#     #         self.state = result.state
#
#     # @rule()
#     # def start_ordering(self, ):
#     #     cmd = Command(tag='start_ordering', args={})
#     #     result = step(self.state, cmd)
#     #     if result.ok:
#     #         self.state = result.state
#
# TestModel = ModelStateMachine.TestCase


def replay_trace(commands: list[tuple[str, dict[str, Any]]]) -> list[StepResult]:
    """Replay a trace of commands and return results."""
    results: list[StepResult] = []
    s = init_state()
    for tag, args in commands:
        cmd = Command(tag=tag, args=args)
        result = step(s, cmd)
        results.append(result)
        if result.ok and result.state is not None:
            s = result.state
        else:
            break
    return results


if __name__ == '__main__':
    # Quick sanity check
    s0 = init_state()
    ok, failed = check_invariants(s0)
    print(f'Initial state: {s0}')
    print(f'Invariants OK: {ok}')
    if not ok:
        print(f'  Failed: {failed}')
