"""
Auto-generated Python reference model for: task_state_fsm
IR hash: sha256:ebaf531b5f5a668f8f137aa02d42e0b89a662340e52338611f1b27a03295f7d8

Generated by ESSO (Evolutionary Spec Search Optimizer)

This file is standalone and has no ESSO dependencies.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Literal, Mapping


# Domain enums
STATE_SYMBOLS = ('PENDING', 'RUNNING', 'RESTARTING', 'STOPPED', 'FAILED')


@dataclass(frozen=True)
class State:
    """Model state."""
    has_error: bool
    max_restarts: int
    restart_count: int
    state: str


@dataclass(frozen=True)
class Command:
    """Command to execute."""
    tag: Literal('cancel_restarting', 'cancel_running', 'complete_task', 'crash_and_restart', 'crash_max_restarts', 'restart_complete', 'start_task')
    args: Mapping[str, Any]


@dataclass(frozen=True)
class StepResult:
    """Result of a step execution."""
    ok: bool
    state: State | None = None
    effects: Mapping[str, Any] | None = None
    error: str | None = None


def init_state() -> State:
    """Return the initial state."""
    return State(
        has_error=False,
        max_restarts=5,
        restart_count=0,
        state='PENDING',
    )


def check_invariants(s: State) -> tuple[bool, str | None]:
    """Check all invariants. Returns (ok, first_failed_id)."""
    if not (isinstance(s.has_error, bool)):
        return False, 'domain_has_error'
    if not (isinstance(s.max_restarts, int) and not isinstance(s.max_restarts, bool) and 1 <= s.max_restarts <= 10):
        return False, 'domain_max_restarts'
    if not (isinstance(s.restart_count, int) and not isinstance(s.restart_count, bool) and 0 <= s.restart_count <= 10):
        return False, 'domain_restart_count'
    if not (s.state in ('PENDING', 'RUNNING', 'RESTARTING', 'STOPPED', 'FAILED')):
        return False, 'domain_state'
    if not (((not ('FAILED' == s.state)) or ((True == s.has_error) or (s.restart_count >= s.max_restarts)))):
        return False, 'failed_max_restarts'
    if not (((not ('PENDING' == s.state)) or (0 == s.restart_count))):
        return False, 'pending_no_restarts'
    if not ((s.restart_count <= s.max_restarts)):
        return False, 'restarts_bounded'
    return True, None


def step(s: State, cmd: Command) -> StepResult:
    """Execute a step. Returns StepResult."""
    # Check pre-state invariants
    ok, failed = check_invariants(s)
    if not ok:
        return StepResult(ok=False, error=f'pre-invariant violated: {failed}')

    if cmd.tag == 'cancel_restarting':
        if not (('RESTARTING' == s.state)):
            return StepResult(ok=False, error='guard failed for cancel_restarting')
        # Compute updates (simultaneous)
        new_state = State(
            has_error=s.has_error,
            max_restarts=s.max_restarts,
            restart_count=s.restart_count,
            state='STOPPED',
        )
        effects = {
            'event': 'CANCEL',
        }
        ok, failed = check_invariants(new_state)
        if not ok:
            return StepResult(ok=False, error=f'post-invariant violated: {failed}')
        return StepResult(ok=True, state=new_state, effects=effects)
    elif cmd.tag == 'cancel_running':
        if not (('RUNNING' == s.state)):
            return StepResult(ok=False, error='guard failed for cancel_running')
        # Compute updates (simultaneous)
        new_state = State(
            has_error=s.has_error,
            max_restarts=s.max_restarts,
            restart_count=s.restart_count,
            state='STOPPED',
        )
        effects = {
            'event': 'CANCEL',
        }
        ok, failed = check_invariants(new_state)
        if not ok:
            return StepResult(ok=False, error=f'post-invariant violated: {failed}')
        return StepResult(ok=True, state=new_state, effects=effects)
    elif cmd.tag == 'complete_task':
        if not (('RUNNING' == s.state)):
            return StepResult(ok=False, error='guard failed for complete_task')
        # Compute updates (simultaneous)
        new_state = State(
            has_error=s.has_error,
            max_restarts=s.max_restarts,
            restart_count=s.restart_count,
            state='STOPPED',
        )
        effects = {
            'event': 'COMPLETE',
        }
        ok, failed = check_invariants(new_state)
        if not ok:
            return StepResult(ok=False, error=f'post-invariant violated: {failed}')
        return StepResult(ok=True, state=new_state, effects=effects)
    elif cmd.tag == 'crash_and_restart':
        if not (((s.restart_count < s.max_restarts) and ('RUNNING' == s.state))):
            return StepResult(ok=False, error='guard failed for crash_and_restart')
        # Compute updates (simultaneous)
        new_state = State(
            has_error=True,
            max_restarts=s.max_restarts,
            restart_count=(1 + s.restart_count),
            state='RESTARTING',
        )
        effects = {
            'event': 'CRASH',
        }
        ok, failed = check_invariants(new_state)
        if not ok:
            return StepResult(ok=False, error=f'post-invariant violated: {failed}')
        return StepResult(ok=True, state=new_state, effects=effects)
    elif cmd.tag == 'crash_max_restarts':
        if not ((('RUNNING' == s.state) and (s.restart_count >= s.max_restarts))):
            return StepResult(ok=False, error='guard failed for crash_max_restarts')
        # Compute updates (simultaneous)
        new_state = State(
            has_error=True,
            max_restarts=s.max_restarts,
            restart_count=s.restart_count,
            state='FAILED',
        )
        effects = {
            'event': 'MAX_RESTARTS',
        }
        ok, failed = check_invariants(new_state)
        if not ok:
            return StepResult(ok=False, error=f'post-invariant violated: {failed}')
        return StepResult(ok=True, state=new_state, effects=effects)
    elif cmd.tag == 'restart_complete':
        if not (('RESTARTING' == s.state)):
            return StepResult(ok=False, error='guard failed for restart_complete')
        # Compute updates (simultaneous)
        new_state = State(
            has_error=False,
            max_restarts=s.max_restarts,
            restart_count=s.restart_count,
            state='RUNNING',
        )
        effects = {
            'event': 'RESTART',
        }
        ok, failed = check_invariants(new_state)
        if not ok:
            return StepResult(ok=False, error=f'post-invariant violated: {failed}')
        return StepResult(ok=True, state=new_state, effects=effects)
    elif cmd.tag == 'start_task':
        if not (('PENDING' == s.state)):
            return StepResult(ok=False, error='guard failed for start_task')
        # Compute updates (simultaneous)
        new_state = State(
            has_error=False,
            max_restarts=s.max_restarts,
            restart_count=s.restart_count,
            state='RUNNING',
        )
        effects = {
            'event': 'START',
        }
        ok, failed = check_invariants(new_state)
        if not ok:
            return StepResult(ok=False, error=f'post-invariant violated: {failed}')
        return StepResult(ok=True, state=new_state, effects=effects)
    else:
        return StepResult(ok=False, error=f'unknown action: {cmd.tag}')


# === Hypothesis test scaffolding ===
# Uncomment and install hypothesis to use property-based testing

# from hypothesis import given, strategies as st
# from hypothesis.stateful import RuleBasedStateMachine, rule, initialize
#
# class ModelStateMachine(RuleBasedStateMachine):
#     def __init__(self):
#         super().__init__()
#         self.state = init_state()
#
#     @initialize()
#     def init(self):
#         self.state = init_state()
#         ok, _ = check_invariants(self.state)
#         assert ok, 'init violates invariants'
#
#     # @rule()
#     # def cancel_restarting(self, ):
#     #     cmd = Command(tag='cancel_restarting', args={})
#     #     result = step(self.state, cmd)
#     #     if result.ok:
#     #         self.state = result.state
#
#     # @rule()
#     # def cancel_running(self, ):
#     #     cmd = Command(tag='cancel_running', args={})
#     #     result = step(self.state, cmd)
#     #     if result.ok:
#     #         self.state = result.state
#
#     # @rule()
#     # def complete_task(self, ):
#     #     cmd = Command(tag='complete_task', args={})
#     #     result = step(self.state, cmd)
#     #     if result.ok:
#     #         self.state = result.state
#
#     # @rule()
#     # def crash_and_restart(self, ):
#     #     cmd = Command(tag='crash_and_restart', args={})
#     #     result = step(self.state, cmd)
#     #     if result.ok:
#     #         self.state = result.state
#
#     # @rule()
#     # def crash_max_restarts(self, ):
#     #     cmd = Command(tag='crash_max_restarts', args={})
#     #     result = step(self.state, cmd)
#     #     if result.ok:
#     #         self.state = result.state
#
#     # @rule()
#     # def restart_complete(self, ):
#     #     cmd = Command(tag='restart_complete', args={})
#     #     result = step(self.state, cmd)
#     #     if result.ok:
#     #         self.state = result.state
#
#     # @rule()
#     # def start_task(self, ):
#     #     cmd = Command(tag='start_task', args={})
#     #     result = step(self.state, cmd)
#     #     if result.ok:
#     #         self.state = result.state
#
# TestModel = ModelStateMachine.TestCase


def replay_trace(commands: list[tuple[str, dict[str, Any]]]) -> list[StepResult]:
    """Replay a trace of commands and return results."""
    results: list[StepResult] = []
    s = init_state()
    for tag, args in commands:
        cmd = Command(tag=tag, args=args)
        result = step(s, cmd)
        results.append(result)
        if result.ok and result.state is not None:
            s = result.state
        else:
            break
    return results


if __name__ == '__main__':
    # Quick sanity check
    s0 = init_state()
    ok, failed = check_invariants(s0)
    print(f'Initial state: {s0}')
    print(f'Invariants OK: {ok}')
    if not ok:
        print(f'  Failed: {failed}')
