"""
Auto-generated Python reference model for: threshold_gate_kernel
IR hash: sha256:6dc3a17a92ecd510b338e6e2d104535785f02288695949e514971726d036614e

Generated by ESSO (Evolutionary Spec Search Optimizer)

This file is standalone and has no ESSO dependencies.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Literal, Mapping


@dataclass(frozen=True)
class State:
    """Model state."""
    close_threshold: int
    current_value: int
    gate_open: bool
    open_threshold: int


@dataclass(frozen=True)
class Command:
    """Command to execute."""
    tag: Literal('close_gate', 'decrease_value', 'increase_value', 'open_gate')
    args: Mapping[str, Any]


@dataclass(frozen=True)
class StepResult:
    """Result of a step execution."""
    ok: bool
    state: State | None = None
    effects: Mapping[str, Any] | None = None
    error: str | None = None


def init_state() -> State:
    """Return the initial state."""
    return State(
        close_threshold=20,
        current_value=0,
        gate_open=False,
        open_threshold=80,
    )


def check_invariants(s: State) -> tuple[bool, str | None]:
    """Check all invariants. Returns (ok, first_failed_id)."""
    if not (isinstance(s.close_threshold, int) and not isinstance(s.close_threshold, bool) and 0 <= s.close_threshold <= 49):
        return False, 'domain_close_threshold'
    if not (isinstance(s.current_value, int) and not isinstance(s.current_value, bool) and 0 <= s.current_value <= 100):
        return False, 'domain_current_value'
    if not (isinstance(s.gate_open, bool)):
        return False, 'domain_gate_open'
    if not (isinstance(s.open_threshold, int) and not isinstance(s.open_threshold, bool) and 50 <= s.open_threshold <= 100):
        return False, 'domain_open_threshold'
    if not ((s.close_threshold < s.open_threshold)):
        return False, 'thresholds_ordered'
    if not (((s.current_value <= 100) and (s.current_value >= 0))):
        return False, 'value_bounded'
    return True, None


def step(s: State, cmd: Command) -> StepResult:
    """Execute a step. Returns StepResult."""
    # Check pre-state invariants
    ok, failed = check_invariants(s)
    if not ok:
        return StepResult(ok=False, error=f'pre-invariant violated: {failed}')

    if cmd.tag == 'close_gate':
        if not (((s.current_value < s.close_threshold) and (True == s.gate_open))):
            return StepResult(ok=False, error='guard failed for close_gate')
        # Compute updates (simultaneous)
        new_state = State(
            close_threshold=s.close_threshold,
            current_value=s.current_value,
            gate_open=False,
            open_threshold=s.open_threshold,
        )
        effects = {
            'event': 'CLOSE',
        }
        ok, failed = check_invariants(new_state)
        if not ok:
            return StepResult(ok=False, error=f'post-invariant violated: {failed}')
        return StepResult(ok=True, state=new_state, effects=effects)
    elif cmd.tag == 'decrease_value':
        if not ((s.current_value >= 10)):
            return StepResult(ok=False, error='guard failed for decrease_value')
        # Compute updates (simultaneous)
        new_state = State(
            close_threshold=s.close_threshold,
            current_value=(s.current_value - 10),
            gate_open=s.gate_open,
            open_threshold=s.open_threshold,
        )
        effects = {
            'event': 'UPDATE',
        }
        ok, failed = check_invariants(new_state)
        if not ok:
            return StepResult(ok=False, error=f'post-invariant violated: {failed}')
        return StepResult(ok=True, state=new_state, effects=effects)
    elif cmd.tag == 'increase_value':
        if not ((s.current_value <= 90)):
            return StepResult(ok=False, error='guard failed for increase_value')
        # Compute updates (simultaneous)
        new_state = State(
            close_threshold=s.close_threshold,
            current_value=(10 + s.current_value),
            gate_open=s.gate_open,
            open_threshold=s.open_threshold,
        )
        effects = {
            'event': 'UPDATE',
        }
        ok, failed = check_invariants(new_state)
        if not ok:
            return StepResult(ok=False, error=f'post-invariant violated: {failed}')
        return StepResult(ok=True, state=new_state, effects=effects)
    elif cmd.tag == 'open_gate':
        if not (((False == s.gate_open) and (s.current_value >= s.open_threshold))):
            return StepResult(ok=False, error='guard failed for open_gate')
        # Compute updates (simultaneous)
        new_state = State(
            close_threshold=s.close_threshold,
            current_value=s.current_value,
            gate_open=True,
            open_threshold=s.open_threshold,
        )
        effects = {
            'event': 'OPEN',
        }
        ok, failed = check_invariants(new_state)
        if not ok:
            return StepResult(ok=False, error=f'post-invariant violated: {failed}')
        return StepResult(ok=True, state=new_state, effects=effects)
    else:
        return StepResult(ok=False, error=f'unknown action: {cmd.tag}')


# === Hypothesis test scaffolding ===
# Uncomment and install hypothesis to use property-based testing

# from hypothesis import given, strategies as st
# from hypothesis.stateful import RuleBasedStateMachine, rule, initialize
#
# class ModelStateMachine(RuleBasedStateMachine):
#     def __init__(self):
#         super().__init__()
#         self.state = init_state()
#
#     @initialize()
#     def init(self):
#         self.state = init_state()
#         ok, _ = check_invariants(self.state)
#         assert ok, 'init violates invariants'
#
#     # @rule()
#     # def close_gate(self, ):
#     #     cmd = Command(tag='close_gate', args={})
#     #     result = step(self.state, cmd)
#     #     if result.ok:
#     #         self.state = result.state
#
#     # @rule()
#     # def decrease_value(self, ):
#     #     cmd = Command(tag='decrease_value', args={})
#     #     result = step(self.state, cmd)
#     #     if result.ok:
#     #         self.state = result.state
#
#     # @rule()
#     # def increase_value(self, ):
#     #     cmd = Command(tag='increase_value', args={})
#     #     result = step(self.state, cmd)
#     #     if result.ok:
#     #         self.state = result.state
#
#     # @rule()
#     # def open_gate(self, ):
#     #     cmd = Command(tag='open_gate', args={})
#     #     result = step(self.state, cmd)
#     #     if result.ok:
#     #         self.state = result.state
#
# TestModel = ModelStateMachine.TestCase


def replay_trace(commands: list[tuple[str, dict[str, Any]]]) -> list[StepResult]:
    """Replay a trace of commands and return results."""
    results: list[StepResult] = []
    s = init_state()
    for tag, args in commands:
        cmd = Command(tag=tag, args=args)
        result = step(s, cmd)
        results.append(result)
        if result.ok and result.state is not None:
            s = result.state
        else:
            break
    return results


if __name__ == '__main__':
    # Quick sanity check
    s0 = init_state()
    ok, failed = check_invariants(s0)
    print(f'Initial state: {s0}')
    print(f'Invariants OK: {ok}')
    if not ok:
        print(f'  Failed: {failed}')
